name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches: 
      - "*"
  schedule:
    # Daily at 05:47
    - cron: '47 5 * * *'

env:
  PIP_NO_PYTHON_VERSION_WARNING: 1

jobs:
  test:
    name: ${{ matrix.os.name }} ${{ matrix.python.name }} ${{ matrix.reactor.name }}
    runs-on: ${{ matrix.os.runs-on }}
    container: ${{ matrix.os.container[matrix.python.docker] }}
    env:
      COMMAND: ${{ matrix.python.command }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: Linux
            runs-on: ubuntu-latest
            python_platform: linux
            container:
              2.7: docker://python:2.7-buster
              3.5: docker://python:3.5-buster
              3.6: docker://python:3.6-buster
              3.7: docker://python:3.7-buster
              3.8: docker://python:3.8-buster
              pypy2: docker://pypy:2-jessie
              pypy3: docker://pypy:3-stretch
          - name: Windows
            runs-on: windows-latest
            python_platform: win32
          - name: macOS
            runs-on: macos-latest
            python_platform: darwin
        python:
          - name: CPython 2.7
            tox: py27
            action: 2.7
            docker: 2.7
            command: python2
          - name: CPython 3.5
            tox: py35
            action: 3.5
            docker: 3.5
            command: python3
          - name: CPython 3.6
            tox: py36
            action: 3.6
            docker: 3.6
            command: python3
          - name: CPython 3.7
            tox: py37
            action: 3.7
            docker: 3.7
            command: python3
          - name: CPython 3.8
            tox: py38
            action: 3.8
            docker: 3.8
            command: python3
          - name: PyPy 2
            tox: pypy2
            action: pypy2
            docker: pypy2
            command: pypy2
          - name: PyPy 3
            tox: pypy3
            action: pypy3
            docker: pypy3
            command: pypy3
        reactor:
          - name: default
            tox: default
            dependencies: default
          - name: PyQt5
            tox: pyqt5
            dependencies: qt5
          - name: PySide2
            tox: pyside2
            dependencies: qt5
          - name: asyncio
            tox: asyncio
            dependencies: asyncio
        exclude:
          - python:
              tox: py27
            reactor:
              tox: pyqt5
          - python:
              tox: py27
            reactor:
              tox: pyside2
          - python:
              tox: py27
            reactor:
              tox: asyncio
          - python:
              tox: pypy2
            reactor:
              tox: asyncio
          - python:
              tox: pypy2
            reactor:
              tox: pyqt5
          - python:
              tox: pypy2
            reactor:
              tox: pyside2
          - python:
              tox: pypy3
            reactor:
              tox: pyqt5
          - python:
              tox: pypy3
            reactor:
              tox: pyside2
    steps:
      - uses: actions/checkout@v2
      - name: Enable Problem Matchers
        run: |
          echo "::add-matcher::.github/local-problem-matchers.json"
      - name: Set up ${{ matrix.python.name }}
        if: ${{ job.container == '' }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python.action }}
          architecture: x64
      - name: Report Python information
        shell: bash
        run: |
          ${COMMAND} -c 'import sys; print(sys.version)'
          echo
          echo "    <=======>"
          echo
          ${COMMAND} -m pip --version
          echo
          echo "    <=======>"
          echo
          ${COMMAND} -m pip list
          echo
          echo "    <=======>"
          echo
          ${COMMAND} -m pip freeze --all
      - name: Install Linux Qt5 dependencies
        if: matrix.os.python_platform == 'linux' && matrix.reactor.dependencies == 'qt5'
        run: |
          apt-get update --yes
          apt-get install --yes libgl1
      - name: Install
        run: |
          pip install tox
      - name: Test
        run: |
          tox -v -e "${{ matrix.python.tox }}-${{ matrix.reactor.tox }}reactor"
  linting:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - short: 38
            dotted: 3.8
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python.dotted }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python.dotted }}
          architecture: x64
      - name: Install
        run: |
          pip install tox
      - name: Test
        run: |
          tox -v -e linting
  all:
    name: All
    runs-on: ubuntu-latest
    needs:
      - test
      - linting
    steps:
      - name: This
        shell: python
        run: |
          import this
